CREATE TABLE [dbo].[ItemUnit](
	[ID] [int] NOT NULL,
	[ItemID] [int] NOT NULL,
	[QtyPerUnit] [int] NOT NULL,
	[Text] [varchar](50) NOT NULL,
 CONSTRAINT [PK_ItemUnit] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]