 
CREATE TABLE [dbo].[UserCommodityType](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[TypeID] [int] NOT NULL,
 CONSTRAINT [PK_dbo_UserCommodityType_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [U_dbo_UserCommodityType_UserID_TypeID] UNIQUE NONCLUSTERED 
(
	[UserID] ASC,
	[TypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UserCommodityType]  WITH CHECK ADD  CONSTRAINT [FK_dbo_UserCommodityType_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([ID])
GO

ALTER TABLE [dbo].[UserCommodityType] CHECK CONSTRAINT [FK_dbo_UserCommodityType_UserID]
GO

ALTER TABLE [dbo].[UserCommodityType]  WITH CHECK ADD  CONSTRAINT [FK_dbo_UserCommodityType_TypeID] FOREIGN KEY([TypeID])
REFERENCES [dbo].[Type] ([ID])
GO

ALTER TABLE [dbo].[UserCommodityType] CHECK CONSTRAINT [FK_dbo_UserCommodityType_TypeID]
GO



