CREATE TABLE [dbo].[UserStore](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserID] [int] NOT NULL,
	[StoreID] [int] NOT NULL,
 CONSTRAINT [PK_dbo_UserStore_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [U_dbo_UserStore_UserID_TypeID] UNIQUE NONCLUSTERED 
(
	[UserID] ASC,
	[StoreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UserStore]  WITH CHECK ADD  CONSTRAINT [FK_dbo_UserStore_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([ID])
GO

ALTER TABLE [dbo].[UserStore] CHECK CONSTRAINT [FK_dbo_UserStore_UserID]
GO

ALTER TABLE [dbo].[UserStore]  WITH CHECK ADD  CONSTRAINT [FK_dbo_UserStore_StoreID] FOREIGN KEY([StoreID])
REFERENCES [dbo].[Stores] ([ID])
GO

ALTER TABLE [dbo].[UserStore] CHECK CONSTRAINT [FK_dbo_UserStore_StoreID]
GO