CREATE TABLE [dbo].[YearEndDetail](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[YearEndID] [INT] NULL,
	[ReceiveDocID] [INT] NULL, 
	[Quantity] BIGINT NULL,
 CONSTRAINT [PK_YearEndDetail] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

 

 


 