
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using DAL;

namespace BLL
{
	public class GeneralInfo : _GeneralInfo
	{
		public GeneralInfo()
		{
		
		}

        public bool RunQuery(string sql)
        {
            this.FlushData();
            return this.LoadFromRawSql(sql);
            
        }
	}
}
