
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using DAL;
namespace BLL
{
	public class Pallet : _Pallet
	{
		public Pallet()
		{
		
		}

        public void LoadByPalletNumber(string palletNumber)
        {
            this.LoadFromRawSql(String.Format("select * from Pallet where PalletNo = '{0}'",palletNumber));
        }

        public static int GetLastPanelNumber()
        {
            Pallet pl = new Pallet();
            string query = "select max(PalletNo) Last from Pallet";
            pl.LoadFromRawSql(query);
            return Convert.ToInt32(pl.DataRow["Last"]);
        }
    }
}
