
// Generated by MyGeneration Version # (1.2.0.7)

using DAL;
using System;

namespace BLL
{
    public class YearEndDetail : _YearEndDetail
    {
        public YearEndDetail()
        {

        }
    }
}
